### PR TITLE
Formatting list columns and factor columns

### LINKED ISSUE #3: Format for list cols
Maybe `obj_sum` plus colour?

### LINKED ISSUE #22: Format for factors
Same output as character.

### PR DESCRIPTION
**Pull request by krlmlr**
With `style_subtle()`, can be adapted easily. Default columns (including factors) are formatted via `as.character()`.

Closes #3. Closes #22.

### CODE REVIEW

**Comment by krlmlr** [comment]
Example from a previous build: https://travis-ci.org/krlmlr/colformat/builds/259052822#L733, line 733.

**Comment by krlmlr** [comment]
List output: https://travis-ci.org/hadley/colformat/builds/259054975#L751

Factor output: https://travis-ci.org/hadley/colformat/builds/259054975#L720

**Comment by krlmlr** [comment]
@hadley: Please comment on the output.

**Comment by hadley** [comment]
Looks fine for a start. We could probably use more colour in the list col display.

**Comment by krlmlr** [comment]
Magenta?

**Comment by hadley** [comment]
I'd prefer blue or green I think

**Pull request merged**
