### PR TITLE
New multicolformat()

### LINKED ISSUE #21: Handle more than one column
so that printing the body part of a tibble becomes entirely the responsibility of this package.

New constructor: `multicolformat()` or `colformats()`.

@hadley: Do you have a strong opinion against this?

### PR DESCRIPTION
**Pull request by krlmlr**
Responsible for:

- Computing column widths based on overall width constraint
- Printing all columns, underlining the entire header

Closes #21.

Also fixes a few minor glitches.

Unfortunately, Travis CI seems to have problems with rendering underlines. Screenshot attached.

screenshot from 2017-07-31 20-41-30

### CODE REVIEW

**Comment by hadley** [comment]
Where do you see column names fitting into the api?

**Comment by krlmlr** [comment]
I just added column names to the tests: They are used iff the input list is named. Screenshot:

screenshot from 2017-07-31 22-19-15

**Comment by hadley** [comment]
Ok, thanks. Maybe include one character column with longer strings?

**Comment by krlmlr** [comment]
Done, also improved consistency of distribution of remaining space:

screenshot from 2017-08-03 10-49-11

**Comment by hadley** [comment]
I'm not convinced that we should ever make columns less than 5 characters (i.e. the minimum to display most column type abbreviations). It's only going to be useful for logical vectors and very narrow character vectors that also have very short names.

**Comment by krlmlr** [comment]
Screenshot:

screenshot from 2017-08-03 22-30-20

**Pull request merged**
